apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClassName }}
provisioner: rbd.csi.ceph.com
parameters:
  clusterID: {{ (.Values.cephCsiRbd.csiConfig | first).clusterID }}
  pool: {{ .Values.cephPoolName }}
  imageFeatures: layering
  csi.storage.k8s.io/provisioner-secret-name: {{ .Values.secretName }}
  csi.storage.k8s.io/provisioner-secret-namespace: {{ .Release.Namespace }}
  csi.storage.k8s.io/controller-expand-secret-name: {{ .Values.secretName }}
  csi.storage.k8s.io/controller-expand-secret-namespace: {{ .Release.Namespace }}
  csi.storage.k8s.io/node-stage-secret-name: {{ .Values.secretName }}
  csi.storage.k8s.io/node-stage-secret-namespace: {{ .Release.Namespace }}
  volumeNamePrefix: {{ .Values.rbdNamePrefix | quote }}
allowVolumeExpansion: true
mountOptions:
  - discard
