---
- name: Install mc
  ansible.builtin.apt:
    name:
      - mc

- name: Reflect new hostname in /etc/hosts
  ansible.builtin.replace:
    path: /etc/hosts
    regexp: '(\s+){{ ansible_facts["hostname"] }}(\s+.*)?$'
    replace: '\1{{ inventory_hostname }}\2'

- name: Change hostname
  ansible.builtin.hostname:
    name: '{{ inventory_hostname }}'
  notify: Reboot server
