apiVersion: v2
name: efk
description: Elasticsearch, Fluentd and Kibana logging Stack
version: 1.0
kubeVersion: v1.24
dependencies:
  - name: elasticsearch
    version: 7.9.3
    repository: https://helm.elastic.co
  - name: kibana
    version: 7.9.3
    repository: https://helm.elastic.co
    condition: kibana.enabled
  - name: log-router
    version: 0.4.0
    repository: https://registry.example.com/artifactory/generic-helm
    alias: logRouter
annotations:
  appVersionElasticsearch: 7.9.3
  appVersionKibana: 7.9.3
  appVersionFlutend: 1.14.2

